### ISSUE TITLE
Mobile notifications (android specific)

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [atriplex-co/hyalus#52]
iOS has other bottlenecks in the way of notifications so for now ignore that.

**Comment by gidoBOSSftw5731** [comment]
It is configured to do do that (both in the settings and browser) yet
on firefox nightly on android 8.1 stock

**Comment by asineth0** [comment]
Firefox is a meme, especially on mobile. We only really support Chrome, although you're welcome to submit a PR.

Please test on Chrome.

**Comment by gidoBOSSftw5731** [comment]
Tested on chrome (I know, attentive responses) with the same issue, though I don't think this is news. Also tested on android 11 stock fwiw on both browsers

**Comment by asineth0** [comment]
This works now.
