### ISSUE TITLE
[BUG] 2fa QR code has colors inverted

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [atriplex-co/hyalus#74]
Tested on latest appimage on Debian 11.

To replicate:
Go to settings
Click toggle to enable 2fa
Observe that QR code is inverted and will not scan.

Workaround:
Open inspect element
Select QR code and copy the base64 link to it
Open that in a private tab and scan that

(Or type in the code manually like some kind of savage)

**Comment by asineth0** [comment]
This is done on purpose, and works fine with Google Authenticator (which is the recommended client app).
